from selenium.webdriver.common.by import By

USERNAME_FIELD = By.XPATH, '//input[@data-test="username"]'
PASSWORD_FIELD = By.XPATH, '//input[@data-test="password"]'
LOGIN_BUTTON = By.XPATH, '//input[@data-test="login-button"]'

ERROR_MESSAGE = By.XPATH, '//div[@class = "error-message-container error"]'
BUTTON_ADD_TO_CARD = By.XPATH, '//button[@data-test="add-to-cart-sauce-labs-backpack"]'
SHOPPING_CART = By.XPATH, '//span[@class="shopping_cart_badge"]'
SHOPPING_CART_LINK = By.CSS_SELECTOR, 'a.shopping_cart_link'
REMOVE_BUTTON = By.CSS_SELECTOR, '#remove-sauce-labs-backpack'
ITEM_CARD = By.CSS_SELECTOR, 'a#item_4_title_link'
ADD_ITEM = By.NAME, 'add-to-cart-sauce-labs-backpack'
ITEM_IMAGE = By.CSS_SELECTOR, 'img[alt="Sauce Labs Backpack"]'
ITEM_NAME = By.CSS_SELECTOR, '#item_4_title_link'
FILTER_ICON = By.CSS_SELECTOR, 'select[class ="product_sort_container"]'
FILTER_A_TO_Z = By.CSS_SELECTOR, 'div > span > select > option:nth-child(1)'
FILTER_TYPE = By.CSS_SELECTOR, 'span[class ="active_option"]'
BURGER_MENU = By.CSS_SELECTOR, 'button[id="react-burger-menu-btn"]'
ABOUT_BUTTON = By.CSS_SELECTOR, 'a[id= "about_sidebar_link"]'
RESET_APP = By.CSS_SELECTOR, 'a[id = "reset_sidebar_link"]'
CHECKOUT_BUTTON = By.CSS_SELECTOR, 'button.checkout_button'
FIRST_NAME_FIELD = By.XPATH, '//input[@data-test="firstName"]'
LAST_NAME_FIELD = By.XPATH, '//input[@data-test="lastName"]'
ZIPCODE_FIELD = By.XPATH, '//input[@data-test="postalCode"]'
CONTINUE_BUTTON = By.XPATH, '//input[@data-test="continue"]'
FINISH_BUTTON = By.CSS_SELECTOR, 'button[id = "finish"]'
LOGOUT_BUTTON = By.CSS_SELECTOR, 'a[id= "logout_sidebar_link"]'

